export const JWT_TOKEN_KEY = process.env.NEXT_PUBLIC_JWT_TOKEN_KEY!;
export const AUTH_USER_KEY = process.env.NEXT_PUBLIC_AUTH_USER_KEY!;
export const USER_TYPE = process.env.NEXT_PUBLIC_AUTH_USER_TYPE!;

export const FRONTEND_BASE_URL = process.env.NEXT_PUBLIC_FRONTEND_BASE_URL!;

export const AUTH_BACKEND_BASE_URL =
  process.env.NEXT_PUBLIC_AUTH_BACKEND_BASE_URL!;
export const READER_BACKEND_BASE_URL =
  process.env.NEXT_PUBLIC_READER_BACKEND_BASE_URL!;
export const WRITER_BACKEND_BASE_URL =
  process.env.NEXT_PUBLIC_WRITER_BACKEND_BASE_URL!;
